return {
  'rose-pine/neovim',
  name = 'rose-pine',
  config = function()
    require('rose-pine').setup {
      variant = 'moon',
      dark_variant = 'moon',
      dim_inactive_windows = false,
      extend_background_behind_borders = true,
      enable = {
        terminal = true,
        legacy_highlights = true,
        migrations = true,
      },
      styles = {
        bold = true,
        italic = true,
        transparency = false,
      },
      groups = {
        border = 'muted',
        link = 'iris',
        panel = 'surface',
        error = 'love',
        hint = 'iris',
        info = 'foam',
        note = 'pine',
        todo = 'rose',
        warn = 'gold',
        git_add = 'foam',
        git_change = 'rose',
        git_delete = 'love',
        git_dirty = 'rose',
        git_ignore = 'muted',
        git_merge = 'iris',
        git_rename = 'pine',
        git_stage = 'iris',
        git_text = 'rose',
        git_untracked = 'subtle',
        h1 = 'iris',
        h2 = 'foam',
        h3 = 'rose',
        h4 = 'gold',
        h5 = 'pine',
        h6 = 'foam',
      },
      palette = {
        moon = {
          palette = {
            base = '#0a0a0f',
            surface = '#1a1a2e',
            overlay = '#26233a',
            muted = '#6e6a86',
            subtle = '#908caa',
            text = '#ffffff',
            love = '#ff6b6b',
            gold = '#ffd43b',
            rose = '#ffb3b3',
            pine = '#69db7c',
            foam = '#74c0fc',
            iris = '#d4b8ff',
            highlight_low = '#21202e',
            highlight_med = '#403d52',
            highlight_high = '#524f67',
          },
        },
      },
      highlight_groups = {
        CursorLine = { bg = '#1a1a2e' },
        Visual = { bg = '#26233a' },
        Search = { bg = '#d4b8ff', fg = '#0a0a0f' },
        IncSearch = { bg = '#ffd43b', fg = '#0a0a0f' },
        StatusLine = { bg = '#1a1a2e', fg = '#ffffff' },
        StatusLineNC = { bg = '#0a0a0f', fg = '#6e6a86' },
        TabLine = { bg = '#0a0a0f', fg = '#6e6a86' },
        TabLineSel = { bg = '#1a1a2e', fg = '#ffffff' },
        TabLineFill = { bg = '#0a0a0f' },
        Normal = { bg = '#0a0a0f', fg = '#ffffff' },
        NormalNC = { bg = '#0a0a0f', fg = '#6e6a86' },
        Comment = { fg = '#6e6a86', italic = true },
        Constant = { fg = '#74c0fc' },
        String = { fg = '#69db7c' },
        Character = { fg = '#69db7c' },
        Number = { fg = '#ffd43b' },
        Boolean = { fg = '#ffd43b' },
        Float = { fg = '#ffd43b' },
        Function = { fg = '#d4b8ff' },
        Identifier = { fg = '#74c0fc' },
        Keyword = { fg = '#ff6b6b' },
        Statement = { fg = '#ff6b6b' },
        Operator = { fg = '#d4b8ff' },
        PreProc = { fg = '#ffb3b3' },
        Type = { fg = '#69db7c' },
        Special = { fg = '#d4b8ff' },
        Underlined = { fg = '#74c0fc', underline = true },
        Error = { fg = '#ff6b6b', bg = '#0a0a0f' },
        Todo = { fg = '#ffd43b', bg = '#0a0a0f' },
      },
    }

    vim.cmd 'colorscheme rose-pine'
  end,
}
